### ISSUE TITLE
PR passed, but the job actually failed

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#148]
If I give a project a malformed brigade.js like

```
const { events, Job, Group} = require("brigadier")

function test(e, project) {
  // Create a new job
  var testJob = new Job("test-runner")

  // We want our job to run the stock Docker Python 2 image
  testJob.image = "python:2"

  // Now we want it to run these commands in order:
  testJob.tasks = [
    "pip install -r requirements.txt",
    "python setup.py test"
  ]

  // We're done configuring, so we run the job
  testJob.run()
})

events.on("push", test)
events.on("pull_request", test)
```

In this example, there's an extra closing bracket after the `test` function is closed that should not exist.

The problem is that brigade will accept the webhook from github and immediately return with a green status, even though the build failed:

```
><> k logs brigade-worker-01bz3qz8p79gqbcd5w7f7pp3wf-777301de
yarn run v1.3.2
$ node prestart.js
prestart: src/brigade.js written
$ node --no-deprecation ./dist/src/index.js
/home/src/dist/src/brigade.js:18
})
 ^

SyntaxError: Unexpected token )
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/src/dist/src/index.js:27:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If a brigade pull_request event fails, brigade should send a failure status back to the user.

**Comment by technosophos** [comment]
You are right. At the moment, only the first GitHub status is sent. The feedback channel for both success and failure is not correctly working.

**Comment by bacongobbler** [comment]
closing as a duplicate of #125.
