### ISSUE TITLE
acid-worker: empty-testbed e2e test failing in master

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#53]
<a href="https://github.com/bacongobbler"><img src="https://avatars2.githubusercontent.com/u/1360539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bacongobbler](https://github.com/bacongobbler)**
_2017-09-01 21:31:29_

----

If I kick off a new empty-testbed job using acid-worker from master, I'm seeing:

```
><> k logs acid-worker-01brzct098rr0tp7rk83t6z9wg-033f10f0
yarn start v0.27.5
$ node prestart.js
prestart: src/acid.js written
$ node --no-deprecation ./dist/src/index.js
/home/src/dist/src/acid.js:3
events.on("push", function(e, project) {
^

ReferenceError: events is not defined
    at __dirname (/home/src/dist/src/acid.js:3:1)
    at Object.<anonymous> (/home/src/dist/src/acid.js:54:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/src/dist/src/index.js:27:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
error Command failed with exit code 1.
```

This is because we haven't updated deis/empty-testbed with the new acid.js changes made in https://github.com/deis/acid/commit/2850f4cbc816f6acde8250a8be37175997c41a30.

**Comment by bacongobbler** [comment]
**Comment by [bacongobbler](https://github.com/bacongobbler)**
_2017-09-01 21:33:16_

----

https://github.com/deis/empty-testbed/pull/1
