### ISSUE TITLE
Unexpected string error from prestart.js

### ISSUE THREAD

**Issue by michelleN** [Azure/brigade#627]
I was experiencing the same issue described in #611. Now, I'm using the fix in #621 (built brigade-worker image off master and upgraded brigade in my cluster to use it). This is the error from the log output from my brigade-worker:

```
/home/src/prestart.js:20
  "/etc/brigade-default-script/brigade.js",
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by bacongobbler** [comment]
looks like there's a comma missing on [line 17](https://github.com/Azure/brigade/blob/master/brigade-worker/prestart.js#L17).

**Comment by michelleN** [comment]
omg lol I wish I hadn't deleted my entire set up but I'll build it again and test 😂
